discordbot:
  token: "place your token here"
  #PLAYING, STREAMING, LISTENING, WATCHING
  activitytype: "PLAYING"
  activityname: "with your feelings"
  #ONLINE, IDLE, DND, INVISIBLE
  status: "ONLINE"
  defaultprefix: "!"
  defaultlanguage: "en"

database:
    host: "localhost"
    port: 3306
    database: "database name"
    username: "username"
    password: "password"
    updateperiod: 10 #in seconds